#ifndef USERPREFERENCESANDINSTRUCTIONS_H_INCLUDED
#define USERPREFERENCESANDINSTRUCTIONS_H_INCLUDED

#include "level.h"

void userPreferencesAndInstructions (struct Level * level);

#endif // USERPREFERENCESANDINSTRUCTIONS_H_INCLUDED
