#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define ESCAPE_KEY 27

#define PIXELS_PER_CM 1
#define PIXELS_PER_METER (PIXELS_PER_CM * 100)

#define BALL_RADIUS_CM (4.28/2.0)
#define BALL_RADIUS_PX (BALL_RADIUS_CM * PIXELS_PER_CM)

#define HOLE_RADIUS_CM (10.795/2.0)
#define HOLE_RADIUS_PX (HOLE_RADIUS_CM * PIXELS_PER_CM)

#define BALL_DETAIL_LEVEL 12
#define HOLE_DETAIL_LEVEL 24

#define TARGET_FPS 120.0

#define FRICTION 5.0
#define SPEED_LOST_ON_WALL_IMPACT 0.67

#endif // CONSTANTS_H_INCLUDED
